local config = {
    mod_name = "Pawn Hybrid Vocations AI",
    version = "0.8.5-domain-consolidation",
    debug = {
        enabled = true,
        show_window = false,
        verbose_logging = false,
        log_level = "INFO",
        log_discovery_failures = false,
        write_discovery_file = true,
        discovery_snapshot_interval_seconds = 0.5,
        guild_trace_log_interval_seconds = 0.2,
        discovery_log_path = "PawnHybridVocationsAI\\logs\\PawnHybridVocationsAI.discovery.log",
        targeted_snapshot_limit = 32,
        session_logging_enabled = true,
        session_log_directory = "PawnHybridVocationsAI\\logs",
        session_jsonl_enabled = true,
        session_event_history_limit = 512,
        session_flush_interval_seconds = 0.25,
        session_domain_character = true,
        session_domain_progression = true,
        session_domain_guild = true,
        session_domain_prototype = true,
        session_domain_npc = true,
        session_domain_scene = true,
        session_domain_character_type = true,
        session_domain_job_definitions = true,
        session_domain_skills = true,
        session_domain_equipment = true,
        session_domain_inventory = true,
        session_domain_quest = true,
        session_domain_dialogue = true,
        session_domain_weapon = true,
        session_domain_reference = true,
    },
    discovery = {
        refresh_interval_seconds = 2.0,
    },
    runtime = {
        progression_refresh_interval_seconds = 0.25,
        progression_correlation_refresh_interval_seconds = 0.25,
        hybrid_unlock_refresh_interval_seconds = 0.25,
        ai_data_refresh_interval_seconds = 0.5,
    },
    progression_research = {
        enabled = true,
        trace_history_limit = 24,
        enable_runtime_hooks = false,
        enable_runtime_qualification_mirror_probe = false,
        enable_progression_bit_mirror_probe = true,
    },
    vocation_research = {
        enabled = true,
        trace_history_limit = 24,
        enable_runtime_hooks = true,
    },
    ability_research = {
        enabled = true,
        trace_history_limit = 24,
    },
    action_research = {
        enabled = true,
        trace_history_limit = 24,
        pack_snapshot_field_limit = 12,
        packhandler_snapshot_limit = 6,
        filter_unknown_social_spam = true,
        observe_unknown_request_actions = false,
        observe_unknown_actinter = false,
        decision_probe_actions = { "Strafe", "NormalLocomotion" },
        decision_hook_strict_target_mode = true,
        decision_hook_raw_log_limit = 6,
        decision_hook_unmatched_log_limit = 6,
        decision_hook_arg_dump_limit = 5,
        enable_main_pawn_job07_carrier_trace = true,
    },
    combat_research = {
        enabled = true,
        trace_history_limit = 24,
        enable_runtime_hooks = false,
        enable_general_combat_baseline = true,
        enable_forced_skill_probe = false,
    },
    main_pawn = {
        deep_refresh_interval_seconds = 0.5,
    },
    guild_research = {
        enabled = true,
        refresh_interval_seconds = 0.25,
        snapshot_limit = 48,
        tracked_field_limit = 16,
        event_history_limit = 24,
        field_history_limit = 8,
        enable_job_menu_ui_hooks = false,
        enable_dynamic_hooks = false,
        enable_source_method_hooks = false,
        enable_source_probe_once = true,
        enable_aggressive_hook_session = true,
        enable_auto_aggressive_hook_session = true,
        aggressive_hook_session_duration_seconds = 3600.0,
        aggressive_hook_session_event_limit = 20000,
        aggressive_hook_session_auto_cooldown_seconds = 20.0,
        source_snapshot_history_limit = 24,
        source_probe_job_capture_limit = 8,
        source_probe_get_job_info_limit = 8,
        source_probe_add_normal_limit = 16,
        source_probe_get_job_info_player_limit = 8,
        source_probe_get_job_info_main_pawn_limit = 8,
        source_probe_add_normal_player_limit = 8,
        source_probe_add_normal_main_pawn_limit = 8,
        enable_player_job_list_override = false,
        copy_player_item_list_for_main_pawn = true,
        enable_prune_bypass_probe = false,
        enable_post_prune_reinjection = false,
        enable_manual_prune_rewrite = false,
        enable_multi_intervention_probe = false,
        enable_job_info_pawn_override = true,
    },
    npc_spawn = {
        enabled = true,
        spawn_ui_enabled = false,
        template_character_id = "ch230000_01",
        template_prefab_id = "ch230000_01",
        spawn_job = 7,
        human_enemy_combat_param_id = 1,
        sigurd_chara_id = 1108605478,
    },
    install = {
        supports_manual_install = true,
        supports_fluffy_manager = true,
        requires_reframework = true,
        requires_scriptcore = false,
    },
    jobs = {
        mystic_spearhand = 7,
        magick_archer = 8,
        trickster = 9,
        warfarer = 10,
    },
    hybrid_unlock = {
        prototype_enabled = false,
        prototype_mode = "vanilla_guild_only",
        auto_apply_target_job = false,
        auto_qualify_target_job = true,
        request_job_notice = true,
        cleanup_equipment_after_apply = true,
        target_job = 7,
        apply_interval_seconds = 1.5,
        include_trickster = true,
        include_warfarer = true,
    },
    synthetic_job07_adapter = {
        enabled = true,
        profile_key = "job07_sigurd_phased",
        target_job = 7,
        rotate_attacks = false,
        engage_cooldown_seconds = 0.75,
        cooldown_seconds = 6.0,
        max_hold_seconds = 1.0,
        request_skip_think = true,
        observation_ticks = 8,
        release_idle_pack_path = "AppSystem/AI/ActionInterface/ActInterPackData/Common/Idle.user",
        release_combat_pack_path = "AppSystem/AI/ActionInterface/ActInterPackData/Common/MoveToPosition_Walk_Target.user",
        skip_log_limit = 8,
    },
    pawn_ai_data_research = {
        enabled = true,
        tracked_jobs = { 1, 7 },
        snapshot_field_limit = 16,
        interesting_field_limit = 8,
        recursive_scan_depth = 2,
        recursive_scan_field_limit = 16,
        branch_limit = 12,
        phase_post_combat_window_seconds = 2.5,
        comparison_enabled = true,
    },
    ai = {
        active_profile = "research_baseline",
        active_adapter = "ai.job07.synthetic_carrier_adapter",
        enable_runtime_adapters = true,
        enable_experimental_branches = true,
        enable_synthetic_layer = true,
        enable_registry_diagnostics = true,
    },
}

return config
