local config = {
    mod_name = "Pawn Hybrid Vocations AI",
    version = "2.0.0-alpha24-preservation",
    debug = {
        log_level = "INFO",
        file_logging_enabled = true,
        file_log_directory = "PawnHybridVocationsAI/logs",
        file_log_prefix = "PawnHybridVocationsAI.session",
        max_file_logs = 10,
        file_log_flush_interval_seconds = 0.35,
    },
    runtime = {
        progression_refresh_interval_seconds = 0.25,
        hybrid_unlock_refresh_interval_seconds = 0.25,
        combat_refresh_interval_seconds = 0.05,
    },
    hybrid_unlock = {
        target_job = 7,
        auto_mirror_player_hybrid_bits = true,
        enable_guild_job_info_pawn_override = true,
    },
    combat = {
        enabled = true,
        supported_job_ids = {
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
        },
        context_grace_seconds = 0.75,
        target_cache_ttl_seconds = 0.85,
        active_target_cache_ttl_seconds = 2.75,
        lock_target_while_active = true,
        default_move_cooldown_seconds = 0.95,
        failed_move_cooldown_seconds = 0.45,
        selection_log_interval_seconds = 1.25,
        target_log_interval_seconds = 1.25,
        snapshot_log_interval_seconds = 2.00,
        no_target_log_interval_seconds = 2.50,
        skip_think_interval_seconds = 0.18,
        hold_reissue_interval_seconds = 0.18,
        max_reissue_count = 4,
        allow_crash_prone_moves = false,
        damage_telemetry_enabled = true,
        damage_assist_enabled = true,
        damage_assist_multiplier = 1.00,
        damage_assist_minimum_damage = 42.0,
        damage_assist_required_target_match = true,
        direct_damage_fallback_enabled = true,
        direct_damage_fallback_minimum_damage = 42.0,
        direct_damage_fallback_max_distance = 3.50,
        wrong_target_hit_cooldown_seconds = 1.25,
        allow_unresolved_job_level_for_core_moves = true,
        magic_bind_hit_window_seconds = 1.25,
        basic_chain_override_max_distance = 3.35,
        native_basic_chain_takeover_delay_seconds = 0.28,
        basic_chain_native_output_tokens = {
            "job07_shortrangeattack",
            "job07_shortrangeheavyattack",
            "job07_longrangeheavyattack",
            "runattacknormal",
            "run_blade4",
        },
        use_lock_on_target = true,
        use_order_target_controller = true,
        respect_native_job_output = true,
        request_skip_think = true,
        brain_default_recovery_seconds = 0.32,
        brain_hit_recovery_seconds = 0.22,
        brain_opener_recovery_seconds = 0.18,
        brain_burst_recovery_seconds = 0.38,
        brain_no_damage_recovery_seconds = 0.52,
        brain_wrong_target_recovery_seconds = 0.72,
        brain_failure_recovery_seconds = 0.58,
    },
}

return config
