local state = {
    initialized = false,
    last_discovery_refresh = 0.0,
    discovery = {
        managers = {},
        type_defs = {},
        main_pawn = {
            source = "unresolved",
            candidate_count = 0,
            errors = {},
            character_source = "unresolved",
            candidate_paths = {},
        },
        party = {},
    },
    runtime = {
        -- Runtime cache is intentionally centralized here because most research modules
        -- exchange resolved game objects through shared state rather than direct imports.
        main_pawn = nil,
        main_pawn_data = nil,
        player = nil,
        progression_gate_data = nil,
        progression_state_data = nil,
        progression_trace_data = nil,
        progression_probe_data = nil,
        job_gate_correlation_data = nil,
        loadout_research_data = nil,
        vocation_research_data = nil,
        ability_research_data = nil,
        action_research_data = nil,
        synthetic_job07_adapter_data = nil,
        pawn_ai_data_research_data = nil,
        combat_research_data = nil,
        npc_spawn_prototype_data = nil,
        sigurd_observer_data = nil,
        hybrid_unlock_data = nil,
        hybrid_unlock_research_data = nil,
        hybrid_unlock_prototype_data = nil,
        guild_flow_research_data = nil,
        last_guild_flow_refresh = 0.0,
        guild_trace_event_id = 0,
        talk_event_trace_data = nil,
        game_time = 0.0,
        delta_time = 0.0,
        session_log_data = nil,
        scheduler = {},
        module_registry = nil,
        last_main_pawn_identity_signature = nil,
        last_main_pawn_deep_refresh = 0.0,
        last_progression_state_signature = nil,
        last_job_gate_correlation_signature = nil,
    },
}

return state
